version: '3.8'

services:
  neo4j_db:
    image: neo4j:5.19
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    networks:
      - ems_network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "$$(cat /run/secrets/neo4j_auth_file | cut -d'/' -f2)", "SHOW DATABASES"]

  web_backend:
    build: ./web_backend
    depends_on:
      neo4j_db:
        condition: service_healthy
    networks:
      - ems_network

networks:
  ems_network:
    driver: bridge

secrets:
  neo4j_auth_file:
    external: true  # Production uses external secrets
