version: '3.8'

services:
  neo4j_db:
    image: neo4j:5.19
    container_name: neo4j_db
    environment:
      - NEO4J_AUTH=neo4j/your_password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data
      - ./lookup_codes:/import
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    networks:
      - ems_network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "your_password", "SHOW DATABASES"]
      interval: 10s
      timeout: 10s
      retries: 5

  web_backend:
    build: ./web_backend
    container_name: web_backend
    depends_on:
      neo4j_db:
        condition: service_healthy
    volumes:
      - ./web_backend/app/uploads:/app/uploads
      - ./queries:/queries
      - ./config.ini:/app/config.ini
    ports:
      - "8000:8000"
    networks:
      - ems_network

volumes:
  neo4j_data:

networks:
  ems_network:
    driver: bridge
