services:
  neo4j-db:
    image: neo4j:5.19
    container_name: neo4j-db
    environment:
      - NEO4J_AUTH=neo4j/myPassword
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ../../nfirs_lookup_codes:/import/nfirs_lookup_codes
      - ../../uploads:/import/uploads
      - neo4j_data:/data
    secrets:
      - neo4j_auth_file
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://neo4j-db:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ems_network

  data_importer:
    image: neo4j:5.19
    depends_on:
      neo4j-db:
        condition: service_healthy
    volumes:
      - ../../scripts/import_lookup_nodes.sh:/import_lookup_nodes.sh
      - ../../nfirs_lookup_codes:/import/nfirs_lookup_codes
    secrets:
      - neo4j_auth_file
    command: ["sh", "/import_lookup_nodes.sh"]
    networks:
      - ems_network

  web_backend:
    build: ../../web_backend
    container_name: web_backend
    depends_on:
      neo4j-db:
        condition: service_healthy
    volumes:
      - ../../uploads:/app/uploads
      - ../../queries/:/queries/
    networks:
      - ems_network

secrets:
  neo4j_auth_file:
    file: ../secrets/neo4j_auth.txt

networks:
  ems_network:
    driver: bridge

volumes:
  neo4j_data:
