services:
  neo4j_db:
    image: neo4j:5.19
    container_name: neo4j_db
    environment:
      - EXTENSION_SCRIPT=/entrypoint.sh
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ../neo4j/entrypoint.sh:/entrypoint.sh:ro
      - ../../nfirs_lookup_codes:/import
      - neo4j_data:/data
    secrets:
      - neo4j_auth_file
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ems_network

  web_backend:
    build: ../../web_backend
    container_name: web_backend
    depends_on:
      neo4j_db:
        condition: service_healthy
    volumes:
      - ./web_backend/app/uploads:/app/uploads
      - ./queries:/queries
    networks:
      - ems_network

volumes:
  neo4j_data:

secrets:
  neo4j_auth_file:
    file: ../secrets/neo4j_auth.txt

networks:
  ems_network:
    driver: bridge
